export default {
  REFRESH_HOT_MOVIE: 'REFRESH_MOVIE',
  REFRESH_WEEKLY_MOVIE: 'REFRESH_WEEKLY_MOVIE',
  NET_ERROR: 'NET_ERROR',
  MOVIE_DETAIL: 'MOVIE_DETAIL',
  MOVIE_COMMENT: 'MOVIE_COMMENT',
  MOVIE_COMMENT_LOADING_MORE: 'MOVIE_COMMENT_LOADING_MORE'
}
